language: cpp

# os:
#  - linux
#  - osx

compiler:
#  - gcc
  - clang

env:
  - CGAL_VERSION=4.3
  - CGAL_VERSION=4.7

# new infrastructure
sudo: false

# cache CGAL
cache:
  directories:
  - $HOME/CGAL-4.3
  - $HOME/CGAL-4.7

addons:
  apt:
    sources:
    - boost-latest
    - kalakris-cmake
    packages:
    - cmake
    - libboost-chrono1.53-dev
    - libboost-program-options1.53-dev
    - libboost-filesystem1.53-dev
    - libboost-timer1.53-dev
    - libboost-test1.53-dev
    - libboost-date-time1.53-dev
    - libboost-thread1.53-dev
    - libboost-system1.53-dev
    - libboost-serialization1.53-dev
    - libmpfr-dev
    - libgmp-dev

before_install:
  - bash ./travis/${TRAVIS_OS_NAME}/install_cgal.sh $CGAL_VERSION

before_script:
  - export CGAL_DIR=$HOME/CGAL-${CGAL_VERSION}
  - cmake -DSFCGAL_BUILD_TESTS=ON

script:
  - make
  - make test
