language: cpp

# os:
#  - linux
#  - osx

compiler:
  - gcc
  - clang

before_install:
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh

before_script:
  - cmake -DSFCGAL_BUILD_TESTS=ON

script:
  - make
  - make test
