language: cpp 
dist: trusty 
sudo: required 

# os:
#  - linux
#  - osx

compiler:
#  - gcc
  - clang

env:
  - CGAL_VERSION=4.10.2
  - CGAL_VERSION=4.11

before_install:
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh $CGAL_VERSION

before_script:
  - CGAL_DIR=/usr/local/lib/CGAL cmake -DSFCGAL_BUILD_TESTS=ON

script:
  - make
  - ctest -VV
